package flexitModbus

func GetAllInputRegisters() map[string]FlexitRegister {
	return map[string]FlexitRegister{
		"GWYVer": FlexitRegister{
			Address:     0,
			Name:        "GWYVer",
			Format:      "UINT 16",
			Description: "Protokollversion.",
			Write:       false,
			Unit:        "",
			Default:     0,
			Min:         0,
			Max:         0xffff,
		},

		"CUHWType": FlexitRegister{
			Address:     1,
			Name:        "CUHWType",
			Format:      "UINT 16",
			Description: "Main board hardware type",
			Write:       false,
			Unit:        "",
			Default:     0,
			Min:         0,
			Max:         0xffff,
		},

		"CUSWRev": FlexitRegister{
			Address:     2,
			Name:        "CUSWRev",
			Format:      "UINT 16",
			Description: "Main board software rev.",
			Write:       false,
			Unit:        "",
			Default:     0,
			Min:         0,
			Max:         0xffff,
		},

		"CPASWRev": FlexitRegister{
			Address:     3,
			Name:        "CPASWRev",
			Format:      "UINT 16",
			Description: "CPA board software rev.",
			Write:       false,
			Unit:        "",
			Default:     0,
			Min:         0,
			Max:         0xffff,
		},

		"CPB1SWRev": FlexitRegister{
			Address:     4,
			Name:        "CPB1SWRev",
			Format:      "UINT 16",
			Description: "CPB1 board software rev. (Norm. GB)",
			Write:       false,
			Unit:        "",
			Default:     0,
			Min:         0,
			Max:         0xffff,
		},

		"CBPS2WRev": FlexitRegister{
			Address:     5,
			Name:        "CBPS2WRev",
			Format:      "UINT 16",
			Description: "CPB2 board software rev. (if installed)",
			Write:       false,
			Unit:        "",
			Default:     0,
			Min:         0,
			Max:         0xffff,
		},

		"Time1": FlexitRegister{
			Address:     6,
			Name:        "Time1",
			Format:      "UINT 32",
			Description: "Real time clock value",
			Write:       false,
			Unit:        "",
			Default:     0,
			Min:         0,
			Max:         0xffffffff,
		},

		"FilterTimer": FlexitRegister{
			Address:     8,
			Name:        "FilterTimer",
			Format:      "UINT 16",
			Description: "Filter timer",
			Write:       false,
			Unit:        "h",
			Default:     0,
			Min:         0,
			Max:         0xffff,
		},

		"SupplyAirTemp": FlexitRegister{
			Address:     9,
			Name:        "SupplyAirTemp",
			Format:      "INT 16",
			Description: "Supply air temperature",
			Write:       false,
			Unit:        "0.1°C",
			Default:     20,
			Min:         -45,
			Max:         50,
		},

		"ExtractAirTemp": FlexitRegister{
			Address:     10,
			Name:        "ExtractAirTemp",
			Format:      "INT 16",
			Description: "Extract air temperature",
			Write:       false,
			Unit:        "0.1°C",
			Default:     20,
			Min:         -45,
			Max:         50,
		},

		"OutdoorAirTemp": FlexitRegister{
			Address:     11,
			Name:        "OutdoorAirTemp",
			Format:      "INT 16",
			Description: "Outdoor air temperature",
			Write:       false,
			Unit:        "0.1°C",
			Default:     20,
			Min:         -45,
			Max:         50,
		},

		"ReturnWaterTemp": FlexitRegister{
			Address:     12,
			Name:        "ReturnWaterTemp",
			Format:      "INT 16",
			Description: "Return water temperature",
			Write:       false,
			Unit:        "0.1°C",
			Default:     20,
			Min:         -45,
			Max:         50,
		},

		"Cooling": FlexitRegister{
			Address:     13,
			Name:        "Cooling",
			Format:      "INT 16",
			Description: "Cooling",
			Write:       false,
			Unit:        "%",
			Default:     45,
			Min:         0,
			Max:         100,
		},

		"HeatExchanger": FlexitRegister{
			Address:     14,
			Name:        "HeatExchanger",
			Format:      "INT 16",
			Description: "Heat exchanger",
			Write:       false,
			Unit:        "%",
			Default:     45,
			Min:         0,
			Max:         100,
		},

		"Heating": FlexitRegister{
			Address:     15,
			Name:        "Heating",
			Format:      "INT 16",
			Description: "Heating",
			Write:       false,
			Unit:        "%",
			Default:     45,
			Min:         0,
			Max:         100,
		},

		"RegulationFanSpeed": FlexitRegister{
			Address:     16,
			Name:        "RegulationFanSpeed",
			Format:      "INT 16",
			Description: "Regulation fan speed",
			Write:       false,
			Unit:        "",
			Default:     0,
			Min:         0,
			Max:         3,
		},

		"OperTime": FlexitRegister{
			Address:     17,
			Name:        "OperTime",
			Format:      "UINT 16",
			Description: "Operational time",
			Write:       false,
			Unit:        "h",
			Default:     0,
			Min:         0,
			Max:         0xffff,
		},

		"FilterResetNo": FlexitRegister{
			Address:     18,
			Name:        "FilterResetNo",
			Format:      "UINT 16",
			Description: "The number of filter resets",
			Write:       false,
			Unit:        "",
			Default:     0,
			Min:         0,
			Max:         0xffff,
		},

		"SupplyAirAlarm": FlexitRegister{
			Address:     19,
			Name:        "SupplyAirAlarm",
			Format:      "INT 16",
			Description: "Supply air sensor range alarm",
			Write:       false,
			Unit:        "bool",
			Default:     0,
			Min:         0,
			Max:         1,
		},

		"ExtractAirAlarm": FlexitRegister{
			Address:     20,
			Name:        "ExtractAirAlarm",
			Format:      "INT 16",
			Description: "Extract air sensor range alarm",
			Write:       false,
			Unit:        "bool",
			Default:     0,
			Min:         0,
			Max:         1,
		},

		"OutsideAirAlarm": FlexitRegister{
			Address:     21,
			Name:        "OutsideAirAlarm",
			Format:      "INT 16",
			Description: "Outside air sensor range alarm",
			Write:       false,
			Unit:        "bool",
			Default:     0,
			Min:         0,
			Max:         1,
		},

		"ReturnWaterAlarm": FlexitRegister{
			Address:     22,
			Name:        "ReturnWaterAlarm",
			Format:      "INT 16",
			Description: "Return water sensor range alarm",
			Write:       false,
			Unit:        "bool",
			Default:     0,
			Min:         0,
			Max:         1,
		},

		"FireThermostatAlarm": FlexitRegister{
			Address:     23,
			Name:        "FireThermostatAlarm",
			Format:      "INT 16",
			Description: "Fire thermostat active alarm",
			Write:       false,
			Unit:        "bool",
			Default:     0,
			Min:         0,
			Max:         1,
		},

		"FireSmokeAlarm": FlexitRegister{
			Address:     24,
			Name:        "FireSmokeAlarm",
			Format:      "INT 16",
			Description: "Fire/smoke detector active alarm",
			Write:       false,
			Unit:        "bool",
			Default:     0,
			Min:         0,
			Max:         1,
		},

		"FreezeProtectionAlarm": FlexitRegister{
			Address:     25,
			Name:        "FreezeProtectionAlarm",
			Format:      "INT 16",
			Description: "Freeze proctection return water alarm (low return water temperature)",
			Write:       false,
			Unit:        "bool",
			Default:     0,
			Min:         0,
			Max:         1,
		},

		"RotorAlarm": FlexitRegister{
			Address:     26,
			Name:        "RotorAlarm",
			Format:      "INT 16",
			Description: "Rotor alarm",
			Write:       false,
			Unit:        "bool",
			Default:     0,
			Min:         0,
			Max:         1,
		},

		"ReplaceFilterAlarm": FlexitRegister{
			Address:     27,
			Name:        "ReplaceFilterAlarm",
			Format:      "INT 16",
			Description: "Replace filters alarm",
			Write:       false,
			Unit:        "bool",
			Default:     0,
			Min:         0,
			Max:         1,
		},

		"HeatingBatteryActive": FlexitRegister{
			Address:     28,
			Name:        "HeatingBatteryActive",
			Format:      "INT 16",
			Description: "Heating battery active",
			Write:       false,
			Unit:        "bool",
			Default:     1,
			Min:         0,
			Max:         1,
		},

		"SchActive": FlexitRegister{
			Address:     29,
			Name:        "SchActive",
			Format:      "INT 16",
			Description: "Scheduler active",
			Write:       false,
			Unit:        "bool",
			Default:     0,
			Min:         0,
			Max:         1,
		},

		"SP0TimeH": FlexitRegister{
			Address:     30,
			Name:        "SP0TimeH",
			Format:      "UINT 32",
			Description: "SP0 Time counter",
			Write:       false,
			Unit:        "s",
			Default:     0,
			Min:         0,
			Max:         0xffffffff,
		},

		"SP1TimeH": FlexitRegister{
			Address:     32,
			Name:        "SP1TimeH",
			Format:      "UINT 32",
			Description: "SP1 Time counter",
			Write:       false,
			Unit:        "s",
			Default:     0,
			Min:         0,
			Max:         0xffffffff,
		},

		"SP2TimeH": FlexitRegister{
			Address:     34,
			Name:        "SP2TimeH",
			Format:      "UINT 32",
			Description: "SP2 Time counter",
			Write:       false,
			Unit:        "s",
			Default:     0,
			Min:         0,
			Max:         0xffffffff,
		},

		"SP3TimeH": FlexitRegister{
			Address:     36,
			Name:        "SP3TimeH",
			Format:      "UINT 32",
			Description: "SP3 Time counter",
			Write:       false,
			Unit:        "s",
			Default:     0,
			Min:         0,
			Max:         0xffffffff,
		},

		"VVX1TimeH": FlexitRegister{
			Address:     38,
			Name:        "VVX1TimeH",
			Format:      "UINT 32",
			Description: "VVX1 Time counter",
			Write:       false,
			Unit:        "s",
			Default:     0,
			Min:         0,
			Max:         0xffffffff,
		},

		"EV1TimeH": FlexitRegister{
			Address:     40,
			Name:        "EV1TimeH",
			Format:      "UINT 32",
			Description: "EV1 Time counter High",
			Write:       false,
			Unit:        "s",
			Default:     0,
			Min:         0,
			Max:         0xffffffff,
		},

		"OperTimeH": FlexitRegister{
			Address:     42,
			Name:        "OperTimeH",
			Format:      "UINT 32",
			Description: "Operational counter High",
			Write:       false,
			Unit:        "s",
			Default:     0,
			Min:         0,
			Max:         0xffffffff,
		},

		"FilterTimeH": FlexitRegister{
			Address:     44,
			Name:        "FilterTimeH",
			Format:      "UINT 32",
			Description: "Filter counter High",
			Write:       false,
			Unit:        "s",
			Default:     0,
			Min:         0,
			Max:         0xffffffff,
		},

		"FilterAlarmPeriod": FlexitRegister{
			Address:     46,
			Name:        "FilterAlarmPeriod",
			Format:      "UINT 16",
			Description: "Filter alarm, time period",
			Write:       false,
			Unit:        "s",
			Default:     180,
			Min:         0,
			Max:         360,
		},

		"ActualSetAirTemperature": FlexitRegister{
			Address:     47,
			Name:        "ActualSetAirTemperature",
			Format:      "INT 16",
			Description: "The set air temperature used on CU",
			Write:       false,
			Unit:        "0.1 °C",
			Default:     200,
			Min:         0,
			Max:         250,
		},

		"ActualSetAirSpeed": FlexitRegister{
			Address:     48,
			Name:        "ActualSetAirSpeed",
			Format:      "INT 16",
			Description: "The set air speed used on CU",
			Write:       false,
			Unit:        "",
			Default:     2,
			Min:         0,
			Max:         3,
		},
	}
}
